### ISSUE TITLE
The CI infrastructure fails on every build

### ISSUE THREAD

**Issue by laszlourszuly** [echsylon/atlantis#2]
The badge is always red.

**Comment by laszlourszuly** [comment]
This is due to the CI environment not supporting the latest Android build tools quite yet. They have a planned upgrade on 28th-29th of April so this issue will most likely solve itself in the next couple of days.

**Comment by echsylon** [comment]
This is due to the CI environment not supporting the latest Android build tools quite yet. They have a planned upgrade on 28th-29th of April so this issue will most likely solve itself in the next couple of days.

**Comment by echsylon** [comment]
The issue seems to be resolved now! Yeay!
