### ISSUE TITLE
Add more log prints in Atlantis

### ISSUE THREAD

**Issue by laszlourszuly** [echsylon/atlantis#36]
Since Atlantis will mostly run in debug builds, it would maybe be a good idea to add more log prints at strategic points in the Atlantis flow. This would enable the developer to better track what is happening "under the hood" and better understand why certain things may not go they way as expected.

**Comment by echsylon** [comment]
This is addressed by version 2.0

Feel free to raise a new ticket describing any shortcomings in this effort.
