### ISSUE TITLE
Put response text in separate files

### ISSUE THREAD

**Issue by AlbinTheander** [echsylon/atlantis#7]
While the single asset file is easy for tiny answers, it quickly gets unreadable when you want the response to a bigger chunk of json or xml. Ideally, it would be possible to put this in a separate file.

Maybe the response config could allow for `text-source` as an alternative to `text`, pointing to an asset file or a resource, e.g. `"text-source": "assets://myfile.json"` or `"text-source" "res://raw/crazy.xml"`.

**Comment by echsylon** [comment]
Of course! Why didn't I think of this? This also reduces the runtime memory footprint of the library while a `text-source` can be read as and when needed, one at a time...
